@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

AddressBook *-left-> "1" UniqueEventList
AddressBook *-right-> "1" UniquePersonList
AddressBook *-down-> "1" UniqueVenueList
AddressBook *-left-> "1" UniqueVendorList

UniquePersonList -down-> "*" person.Person
UniqueEventList -down-> "*" event.Event
UniqueVendorList -down-> "*" vendor.Vendor
UniqueVenueList -down-> "*" venue.Venue

event.Event -right-> "*" person.Person
event.Event -right-> "*" vendor.Vendor
event.Event -right-> "0..1" venue.Venue

event.Event *--> event.Name
event.Event *--> event.Description
event.Event *--> event.Date

person.Person *--> person.Name
person.Person *--> person.Phone
person.Person *--> person.Email

venue.Venue *--> venue.Name
venue.Venue *--> venue.Address
venue.Venue *--> venue.Capacity

vendor.Vendor *--> vendor.Name
vendor.Vendor *--> vendor.Contact
@enduml
